// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tTqxxSNNPLamhhbvK9V5UT
// Component: _BtuFHcHTIyx
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: 8XH6WBEcDkWr/component
import CaseStudiesWraper from "../../CaseStudiesWraper"; // plasmic-import: Ve0ERJ_4OnFN/component
import CtaBottom from "../../CtaBottom"; // plasmic-import: Aj33d4hO6_qo/component
import Footer from "../../Footer"; // plasmic-import: c7_nsHlFJRh2/component
import { useScreenVariants as useScreenVariantshXfVib0KeY9U } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: hXFVib0keY9u/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_professional_services.module.css"; // plasmic-import: tTqxxSNNPLamhhbvK9V5UT/projectcss
import sty from "./PlasmicStories.module.css"; // plasmic-import: _BtuFHcHTIyx/css

createPlasmicElementProxy;

export const PlasmicStories__VariantProps = new Array();

export const PlasmicStories__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStories__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshXfVib0KeY9U()
  });
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__i0ZaG)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Stories"}
              </h1>
            </div>
          </div>
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__edyfy)}>
              <div className={classNames(projectcss.all, sty.freeBox__dn3Lm)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__r7Shu)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"columns"}
                    data-plasmic-override={overrides.columns}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__m7UwY)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__aX4Uh
                        )}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__z4Wb7)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__gApr2
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ob3Vy)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/girls18285391920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__n6Sxs)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__eE9A
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__dk94Z)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/woman32879561920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__sbgd8)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__urYtH
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ssQl)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/girl18484541920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1279,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__wY4U)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__iw2Jw
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___0NUbl)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/girl23664381920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__sijDr)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__uErfQ
                        )}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__kSxX5)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__bOoM
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__o4Epe)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/woman31165871920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1279,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__fERp)}
                    >
                      <CaseStudiesWraper
                        className={classNames(
                          "__wab_instance",
                          sty.caseStudiesWraper__w5KWm
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__yo6Yt)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/professional_services/images/girl17750351920Jpg.jpg",
                            fullWidth: 1920,
                            fullHeight: 1191,
                            aspectRatio: undefined
                          }}
                        />
                      </CaseStudiesWraper>
                    </div>
                  </p.Stack>
                </p.Stack>
              </div>
            </div>
          </section>
          <CtaBottom
            data-plasmic-name={"ctaBottom"}
            data-plasmic-override={overrides.ctaBottom}
            className={classNames("__wab_instance", sty.ctaBottom)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "pageBanerSection",
    "h1",
    "section",
    "columns",
    "ctaBottom",
    "footer"
  ],

  header: ["header"],
  pageBanerSection: ["pageBanerSection", "h1"],
  h1: ["h1"],
  section: ["section", "columns"],
  columns: ["columns"],
  ctaBottom: ["ctaBottom"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStories__ArgProps,
          internalVariantPropNames: PlasmicStories__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStories__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStories";
  } else {
    func.displayName = `PlasmicStories.${nodeName}`;
  }
  return func;
}

export const PlasmicStories = Object.assign(
  // Top-level PlasmicStories renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    h1: makeNodeComponent("h1"),
    section: makeNodeComponent("section"),
    columns: makeNodeComponent("columns"),
    ctaBottom: makeNodeComponent("ctaBottom"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicStories
    internalVariantProps: PlasmicStories__VariantProps,
    internalArgProps: PlasmicStories__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicStories;
/* prettier-ignore-end */
